/** Declaration file generated by dts-gen */

export = koa_bunyan;

declare function koa_bunyan(logger: any, opts: any): any;

declare namespace koa_bunyan {
    const prototype: {
    };

}

