name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - node
          - lts/Hydrogen
          - 18.x
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
